# -*- coding: utf-8 -*-
"""randomPasswordGenerator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7Ku_eoWrEkIqnBF28fJt-TfJkxrv9zv
"""

#DAY ONE OF 20 DAYS CHALLENGE
# import random to generate random password
import random 
import string

def generateRandomPassword():

    sourceRandom =   string.digits + string.punctuation + string.ascii_letters
    pswd = random.choice(string.ascii_lowercase) 
    pswd += random.choice(string.ascii_uppercase)
    pswd += random.choice(string.digits)
    pswd += random.choice(string.punctuation)
    for i in range(5):
        pswd += random.choice(sourceRandom)

    pswdList = list(password)
    random.SystemRandom().shuffle(pswdList)
    pswd = ''.join(pswdList)
    return pswd

print ("Your Random Password is ", randomPassword())

